### ISSUE TITLE
CVV with Token Sale/Auth

### ISSUE THREAD

**Issue by Clearnine** [SagePayments/Direct-API#12]
Scenario:

A new customer comes to the website and we want to tokenize the card, get an authorization, and send the auth information with token into Sage 100's Sales Order Object.

How can we tokenize the card then get an auth using the token and CVV2 information?

This doesn't seem to be possible.  Shouldn't it be?

**Comment by dimante** [comment]
You cannot store the CVV2 code... So it would only work if every time the
customer is going to come back they are going to provide the CVV2 code...

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by Clearnine** [comment]
I get that part.

We are tokenizing the card on the web server, and getting an auth, then sending that token into Sage 100 with the auth info.

How do I tokenize the card, then use said token to get an auth with CVV?

Remember, the scenario is we need to tokenize the card and send that token into Sage 100 with the auth information so the post auth transactions can be handled in Sage 100.

Can I get an auth with the card number directly, then tokenize that card, then send that token to sage 100 with the auth information from the prior step?  Will Sage 100 be able to post auth that?

-Craig

**Comment by dimante** [comment]
You cannot currently get an auth with cvv2. Once you vault the card, you
can present the token again for future payments.  If you are having the
cardholder present each time there is no reason to vault the card.

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by Clearnine** [comment]
Thanks for the reply. 

The issue is we are starting the transaction in one location (the web server).  We want to use CVV2 there.  This could be a completely new customer.  (Existing customers with vaulted cards are a different matter altoghether - we just pick and go.)

Then we send the card info and auth info into Sage 100. We must tokenize the card to do so.  Sage 100 will do the post auth using the tokenized card when the order ships.

Can I get an auth with the card number and CVV2 on the web server, then tokenize the card?  Will the subsequent post auth/capture in Sage 100 function with the tokenized version of the card if I got the auth before I tokenized the card?  It’s not clear to me that this works.  If it does we can do it that way.  

Having said all that there are scenarios when you’d want to require the CVV2 with a vaulted card on a web site.  Apple and Amazon do that to me once in a while.

-Craig

**Comment by dimante** [comment]
I am with you on it but I assure you I have been through this with sage and
all transactions I do with vault do not involve cvv2 at all.  There is
currently not a way to run a vault transaction with cvv2.  We have 2
virtual terminals one with cvv2 and a separate virtual terminal for vault.

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by Clearnine** [comment]
It’s really odd - the other processors we integrate with allow sending a CVV2 with a token to get an auth.  Sage assured me back in October that they were adding this functionality, and I have a couple of pissed off clients that have chargeback issues because we can’t use the CVV2 code on the website because the card MUST be tokenized for storage in the ERP...

Thanks for you replies.

**Comment by dimante** [comment]
I am a customer also... I see it as odd as well.... Unfortunately, that is
what they have available ATM.

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by dimante** [comment]
And again just to preface, you cannot store CVV2 so the cardholder would
have to provide that every time a transaction happened, we do recurring
payment and it would not work in that situation.

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by Clearnine** [comment]
The thing I’m wondering is if I get an auth with the card and cvv info, then tokenize the card, if the post auth/capture will work in the ERP with the token?

**Comment by dimante** [comment]
It will but keep in mind (and I am sorry if I am sounding like a broken
record) you will not have CVV2 for any tokenized transactions.  The same
level of risk will still exist.  So this is exactly how our system works.
We charge initially and ask for the CVV2 at the checkout time.  If there is
a remaining balance, we then tokenize the card and the future remaining
payments are processed with the token and NO CVV2.

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by thlinux1107** [comment]
Wow, it's so great seeing our integrators working so well together to resolve a concern. Clearnine also reached out to us internally for assistance with the CVV2 concern. It appears this issue involves the [Sage Exchange Virtual Desktop (SEVD)](https://developer.sagepayments.com/book/sage-payment-solutions/sage-exchange-virtual-desktop-v20). With SEVD we now have the ability to pass the CVV2 value in a vault/tokenized transaction request. You only need to include the `<AuthCVV>` string in the `<TransactionBase>` node. This allows us to use the CVV2 value during authorization of the tokenized card. I hope this helps. If you have any further questions please feel free to reply to this thread or contact us directly at sdksupport@sage.com.

Thomas Hagan
Integration Consultant, Product Integration
Sage

**Comment by rflores76** [comment]
To "piggy back" on Thomas' response. Although, storing CVV2 is against the PCI regulations we do have a solution to pass CVV2 on a Vault transaction through the Sage Exchange Virtual Desktop. This is the only integration method that offers it. The Direct API and PaymentsJS solutions do not. 

John's solution is the better workaround - Performing an Auth (or Sale) and Vault request will satisfy the initial CVV2 validation. If the validation is a non-match you can Void out the transaction and have the customer or end user re-process the charge.

**Comment by dimante** [comment]
That only works if the cardholder provides it each time a transaction takes
place.  A good add but for recurring payments not a solution :-)

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by dimante** [comment]
Thanks Robert!  It is a workaround that has the security of the cardholder
at the forefront :-)

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by rflores76** [comment]
I am going to add the CVV2 option to our backlog. In the meantime, I would recommend making the CVV2 a required field.

**Comment by Clearnine** [comment]
This has been extremely helpful,  Thanks all.

**Comment by dimante** [comment]
Have a great day!

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by nishakul29** [comment]
Hi,

I have just downloaded your code for Sage payments, I habve run the csharp project but every time I got Invalid HAMC error. the detail error description is attached.

![image](https://user-images.githubusercontent.com/33856711/33058282-f3dd87f8-ceb4-11e7-924e-6d5c8bce5796.png)

Please suggest.


Regards,
Nishant.

**Comment by thlinux1107** [comment]
Nishant,

I've replied via our email conversation that began on 11/15 with this issue. I will summarize here as well.

I just downloaded the sample and ran it without any changes and successfully processed a request (included below). The only item I can think of that can vary without any changes made to the code is the timestamp as that is created based on the system where the code is running. This is also the case for the API Sandbox. Our tolerance for the timestamp is fairly small. I would recommend making sure your system matches internet time within a few seconds. This is not an unusual requirement for secure requests within the payment industry.

Request:
{"Ecommerce":{"OrderNumber":"Invoice 318","Amounts":{"Total":"7"},"CardData":{"Number":"5454545454545454","Expiration":"1220"}}}

Result:
Server Status Code: Created
Server Status: Created
API Response: {"status":"Approved","reference":"FBGH9KnFO0","message":"APPROVED 000007","code":"000007","cvvResult":"P","avsResult":"Y","riskCode":"00","networkId":"10","isPurchaseCard":false,"orderNumber":"Invoice 318","timestamp":"2017-11-16T09:20:48.5251208-05:00"}

SDKSupport
